import type { ProductType } from '../types/productType';

export const products: ProductType[] = [
  {
    id: 1,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 3370,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-01T10:00:00Z',
    retailer: 'TimeZone Watches',
  },

  {
    id: 2,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 500,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-02T12:15:00Z',
    retailer: 'WatchPlanet',
  },

  {
    id: 3,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 230,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-03T14:30:00Z',
    retailer: 'Omega Outlet',
  },

  {
    id: 4,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 90,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-04T09:45:00Z',
    retailer: 'Luxury Timepieces',
  },

  {
    id: 5,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 46,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-05T08:20:00Z',
    retailer: 'ChronoMarket',
  },

  {
    id: 6,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 900,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-06T13:10:00Z',
    retailer: 'ChronoMarket',
  },

  {
    id: 7,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 230,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-07T11:55:00Z',
    retailer: 'WatchHub',
  },

  {
    id: 8,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    retailer: 'Swiss Time Co',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 150,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-08T15:40:00Z',
  },

  {
    id: 9,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 600,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-09T10:05:00Z',
    retailer: 'Elite Watches',
  },

  {
    id: 10,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 60,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-10T16:25:00Z',
    retailer: 'Watch Vault',
  },

  {
    id: 11,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 46,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-11T13:50:00Z',
    retailer: 'TickTock Traders',
  },

  {
    id: 12,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 900,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-12T14:45:00Z',
    retailer: 'LuxuryTime',
  },

  {
    id: 13,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 230,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-13T17:30:00Z',
    retailer: 'WristWorthy',
  },

  {
    id: 14,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 150,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-14T08:15:00Z',
    retailer: 'Timeless Boutique',
  },

  {
    id: 15,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 600,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-15T09:35:00Z',
    retailer: 'Omega Direct',
  },

  {
    id: 16,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 60,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
    createdAt: '2024-11-16T12:00:00Z',
    retailer: 'Global Watch Store',
  },
];
