import type { ProductType } from '../types/productType';

export const products: ProductType[] = [
  {
    id: 1,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 3370.0,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 2,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 500,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 3,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 230,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 4,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 90,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 5,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 46,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 6,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 900,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 7,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 230,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 8,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 150,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 9,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 600,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 10,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 60,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 11,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 46,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 12,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 900,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 13,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 230,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 14,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 150,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 15,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 600,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },

  {
    id: 16,
    name: 'Omega Speedmaster Racing 326.30.40.50.01.002',
    brand: 'Omega',
    model: 'Speedmaster Racing',
    reference: '326.30.40.50.01.002',
    price: 60,
    description: `The Omega Speedmaster Racing 326.30.40.50.01.002 is a 40 mm stainless steel chronograph watch featuring a black dial with silver sub‑dials, sapphire crystal, and tachymeter bezel. Powered by Omega automatic Calibre 3330 with Co‑Axial escapement and 52‑hour power reserve. Water‑resistant to 100 m/330 ft.`,
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    caseThickness: 15,
    bezel: 'Aluminum tachymeter',
    crystal: 'Scratch‑resistant sapphire',
    dialColor: 'Black with silver sub‑dials',
    movement: 'Automatic, Omega calibre 3330, Co‑Axial, chronometer',
    powerReserve: '52 hours',
    waterResistance: '100 m / 330 ft',
    bracelet: 'Stainless steel bracelet, ~19 mm lug',
    functions: ['Chronograph', 'Date', 'Tachymeter'],
  },
];
